website/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField, IntegerField, DateField
from wtforms.validators import DataRequired, Length, NumberRange, EqualTo
from ai_api import generatePlaylist

class InputForm(FlaskForm):
    artist = StringField('Artist', validators=[DataRequired(), Length(max=50)])
    song = StringField('Song Title', validators=[DataRequired(), Length(max=50)])
    number_of_songs = IntegerField('Number of Songs', validators=[DataRequired(), NumberRange(max=20)])
    submit = SubmitField('Submit')

website/__init__.py
from flask import Flask
# from flask_sqlalchemy import SQLAlchemy
# from os import path
import config


def create_app():
    thisApp = Flask(__name__)
    # thisApp.config["SECRET_KEY"] = "build test" #encrypt or secure the cookies
    thisApp.config["SECRET_KEY"] = config.DevelopmentConfig.OPENAI_KEY

    #import the modules
    from .routes import app

    thisApp.register_blueprint(app, url_prefix = "/")

    return thisApp

website/routes.py
from flask import Blueprint, request, render_template, redirect, url_for
from .forms import *
from ai_api import generatePlaylist, parsePlaylist, generateImage

app = Blueprint("routes",__name__)

@app.route('/', methods=['GET', 'POST'])
def index():
    form = InputForm()
    if request.method == 'GET':
        return render_template('index.html', form=form)
    if request.method == 'POST' and form.validate_on_submit:
        artist = form.artist.data
        song = form.song.data
        number_of_songs = form.number_of_songs.data
        playlist = generatePlaylist(artist, song, number_of_songs)
        playlist_dict = parsePlaylist(playlist)
        playlist_pic = generateImage(playlist_dict['dalle_prompt'])
        return render_template('playlist.html', form=form, playlist_name=playlist_dict['playlist_name'],
                               description=playlist_dict['description'],
                               song_title_list=playlist_dict['song_title_list'],
                               artist_list=playlist_dict['artist_list'],
                               playlist_pic=playlist_pic)

website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"  rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
    
    <!-- Our CSS -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <!-- <title>fuel app</title> -->
    {% if title %}
      <title>Playlist Creator AI - {{title}}</title>
    {%else%}
      <title>Playlist Creator AI</title>
    {%endif%}    
  </head>
  <body>
        {% include 'navbar.html' %}
        {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %} 
          {% for category, message in messages %} {% if category =='error' %}
          <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %} {% endfor %} {% endif %} {% endwith %}
        <br/>
        <div class="container">
                {% block content %}
                {% endblock %}
        </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<!--scripts below used for dismissing alert button-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
</body>
</html>

website/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
          <label for="artist">{{ form.artist.label }}</label>
          {{ form.artist(class="form-control", size=32) }}
        </div>
        <div class="form-group">
          <label for="song">{{ form.song.label }}</label>
          {{ form.song(class="form-control", size=32) }}
        </div>
        <div class="form-group">
          <label for="number_of_songs">{{ form.number_of_songs.label }}</label>
          {{ form.number_of_songs(class="form-control", size=32) }}
        </div>        
        {{ form.submit(class="btn btn-secondary") }}
    </form>
</div>
{% endblock %}

website/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('routes.index') }}">Playlist Creator AI</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
  
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('routes.index')}}">Start Creating</a>
            </li>
            
        </ul>
      </div>
    </div>
</nav>

website/templates/playlist.html
{% extends 'base.html' %}

{% block content %}

<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <div class="media">
                <img src="{{ playlist_pic }}" class="rounded float-left mr-3" alt="Playlist Picture">
                <div class="media-body">
                  <h5 class="mt-0">{{ playlist_name }}</h5>
                  {{ description }}
                  {% for i in range(song_title_list|length) %}
                    <a href="#" class="list-group-item rounded">
                        <h4 class="list-group-item-heading">{{ song_title_list[i]  }}</h4>
                        <p class="list-group-item-text">{{ artist_list[i] }}</p>
                    </a>
                  {% endfor %}

                  <!-- {% for song in song_list %}
                  <p for="song_list">
                      {{ song }}
                  </p>
                  {% endfor %} -->
                </div>
              </div>
        </div>
    </form>
</div>

{% endblock %}